pinclone/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView
from pinteresting.views import MyRegistrationBackend
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pinclone.views.home', name='home'),
    # url(r'^pinclone/', include('pinclone.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^users', RedirectView.as_view(url='/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/', MyRegistrationBackend.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('pinteresting.urls', namespace="pinteresting")),
) #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinteresting/urls.py
from django.conf.urls import patterns, url

from pinteresting import views

urlpatterns = patterns('',
    url(r'^$', views.ListPins.as_view(), name="index"), # Index page to show a list of latest entries
    url(r'^add/board/$', views.CreateBoard.as_view(), name='add_board'),
    url(r'^add/pin/$', views.CreatePin.as_view(), name='add_pin'),
    url(r'^repin/(?P<pk>\d+)/$', views.RePin.as_view(), name='repin'),
    url(r'^pin/update/(?P<pk>\d+)/$', views.EditPin.as_view(), name='update_pin'),
    url(r'^pin/delete/(?P<pk>\d+)/$', views.DeletePin.as_view(), name='delete_pin'),
    url(r'^board/(?P<pk>\d+)/$', views.BoardDetail.as_view(), name='board_detail'),
    url(r'^pin/(?P<pk>\d+)/$', views.PinDetail.as_view(), name='pin_detail'),
    url(r'^comment/(?P<pin_id>\d+)/$', views.CreateComment.as_view(), name='add_comment'),
    url(r'^comment/delete/(?P<pk>\d+)/$', views.DeleteComment.as_view(), name='delete_comment'),
    url(r'^comment/update/(?P<pk>\d+)/$', views.EditComment.as_view(), name='update_comment'),
)

pinclone/templates/base.html
{% load staticfiles %}
<!DOCTYPE html> 
<html lang="en"> 
<head> 
	<meta charset="utf-8"> 
	<title>{% block title %}Pinteresting{% endblock %}</title>
	<link href='http://fonts.googleapis.com/css?family=Titillium+Web:600' rel='stylesheet' type='text/css'>
	<link rel ="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<link rel ="stylesheet" href="{% static 'style.css' %}">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script>
	<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
	{% block scripts %}{% endblock %}
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
		<ul class="nav">
		  <li class="active">
		    <a class="brand" href="{% url 'pinteresting:index' %}">Pinteresting</a>
		  </li>
		{% if user.is_authenticated %}
		  <li class="dropdown">
                    <a href="#"
                          class="dropdown-toggle"
                          data-toggle="dropdown">
                          My Boards
                          <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                     {% for board in user_boards %}
                     <li><a href="{% url 'pinteresting:board_detail' board.id %}">{{board.name}}</a></li>
                     {% endfor %}
                    </ul>
                  </li>
		{% endif %}
		  </ul>
		 <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
		    <li><a href="{% url 'pinteresting:add_pin' %}">New Pin</a></li>
		    <li><a href="{% url 'pinteresting:add_board' %}">New Board</a></li>
                    <li><a href="{% url 'auth_logout' %}"> Log Out</a></li>
		    
                    {% else %}
                    <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-user"></span>Log In</a></li>
		    <li><a href="{% url 'registration_register' %}"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
                    {% endif %}
		    {% if user.is_superuser %}
		    <li><a href="{% url 'admin:app_list' 'pinteresting' %}">Admin</a></li>
		    {% endif %}
                </ul>

	    </div>
	  </div>
	</div> 
	<div class="content">
		{% if messages %}
		<div class="messages">
			{% for message in messages %}
				<p class={{message.tags}}>{{message}}</p>
			{% endfor %}
		</div>
		{% endif %}
		{% block content %}

		{% endblock %}
		</div>

		<!--
		<div class="footer">
		Created by: Stephen Goeddel<br />
		On: 11/2/2013
	
		</div>-->
<p style="text-align:center">This web app was made in Django as an exercise, not as an attempt to overtake pinterest.</p>
</body>

</html>