pinclone/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView
from pinteresting.views import MyRegistrationBackend
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pinclone.views.home', name='home'),
    # url(r'^pinclone/', include('pinclone.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^users', RedirectView.as_view(url='/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/', MyRegistrationBackend.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('pinteresting.urls', namespace="pinteresting")),
) #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinteresting/urls.py
from django.conf.urls import patterns, url

from pinteresting import views

urlpatterns = patterns('',
    url(r'^$', views.ListPins.as_view(), name="index"), # Index page to show a list of latest entries
    url(r'^add/board/$', views.CreateBoard.as_view(), name='add_board'),
    url(r'^add/pin/$', views.CreatePin.as_view(), name='add_pin'),
    url(r'^repin/(?P<pk>\d+)/$', views.RePin.as_view(), name='repin'),
    url(r'^pin/update/(?P<pk>\d+)/$', views.EditPin.as_view(), name='update_pin'),
    url(r'^pin/delete/(?P<pk>\d+)/$', views.DeletePin.as_view(), name='delete_pin'),
    url(r'^board/(?P<pk>\d+)/$', views.BoardDetail.as_view(), name='board_detail'),
    url(r'^pin/(?P<pk>\d+)/$', views.PinDetail.as_view(), name='pin_detail'),
    url(r'^comment/(?P<pin_id>\d+)/$', views.CreateComment.as_view(), name='add_comment'),
    url(r'^comment/delete/(?P<pk>\d+)/$', views.DeleteComment.as_view(), name='delete_comment'),
    url(r'^comment/update/(?P<pk>\d+)/$', views.EditComment.as_view(), name='update_comment'),
)

pinteresting/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class Pin(models.Model):
    Colors = (
    ('Red', 'Red'),
    ('Blue', 'Blue'),
    ('Green', 'Green'),
    ('Grey', 'Grey'),
    ('Orange', 'Orange'),
    )


    title = models.CharField(max_length=30)
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/', null=True)
    description = models.TextField()
    created_by = models.ForeignKey(User)
    pub_date = models.DateTimeField(auto_now_add=True)
    link = models.URLField(null=True, blank=True)
    is_public = models.BooleanField(default=True)
    board = models.ManyToManyField('Board')
    color = models.CharField(max_length=10, choices=Colors)

    @property
    def boards(self):
	return Board.objects.all().filter(pin=self)

    @property
    def num_comments(self):
	num = 0
	for comment in Comment.objects.all().filter(pin = self):
		num = num + 1
	return num

    def get_absolute_url(self):
	return reverse('pinteresting:index')

    def __unicode__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(User)
    pin = models.ForeignKey(Pin)
    comment = models.TextField()

    def __unicode__(self):
        return self.comment

    def get_absolute_url(self):
	return reverse('pinteresting:pin_detail', args=(self.pin.id,))

class Board(models.Model):
    created_by = models.ForeignKey(User)
    name = models.CharField(max_length=100)


    @property
    def pins(self):
	return Pin.objects.all().filter(board=self)

    @property
    def public_pins(self):
	return Pin.objects.all().filter(board=self, is_public=True)

    def get_absolute_url(self):
	return reverse('pinteresting:add_pin')

    def __unicode__(self):
        return self.name

pinteresting/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.admin import widgets
from pinteresting.models import Pin, Board, Comment

class AddBoard(ModelForm):
	class Meta:
		model = Board
		fields = ['name']

class AddPin(ModelForm):
	class Meta:
		model = Pin
		exclude = ('pub_date','created_by',)

class Repin(ModelForm):
	class Meta:
		model = Pin
		fields = ['board']

class EditPin(ModelForm):
	class Meta:
		model = Pin
		exclude = ('pub_date','created_by',)

class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = ['comment']

pinteresting/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse, reverse_lazy
from registration.backends.simple.views import RegistrationView
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from endless_pagination.views import AjaxListView

from pinteresting.models import Comment, Board, Pin
from pinteresting.forms import AddBoard, AddPin, Repin, EditPin, CommentForm

class ListPins(AjaxListView):
	template_name = 'pinteresting/index.html'
	model = Pin
	context_object_name = 'pins'
	paginate_by = 5

	def get_queryset(self):
		return Pin.objects.filter(is_public=True).order_by('-pub_date')

	def get_context_data(self, **kwargs):
		user_id = self.request.user.id
		context = super(ListPins, self).get_context_data(**kwargs)
		context['user_boards'] = Board.objects.filter(created_by__id = user_id)
		return context

class BoardDetail(DetailView):
	context_object_name = 'board'
	template_name = 'pinteresting/board_detail.html'

	def get_object(self):
		return get_object_or_404(Board, pk = self.kwargs['pk'])

	def get_context_data(self, **kwargs):
		user_id = self.request.user.id
		board = get_object_or_404(Board, pk = self.kwargs['pk'])
		cur_user = False
		if int(board.created_by.id) == user_id:#make sure this still works when logged in
			cur_user = True
 
		context = super(BoardDetail, self).get_context_data(**kwargs)
		context['user_boards'] = Board.objects.filter(created_by__id = user_id)
		context['cur_user'] = cur_user
		return context

class PinDetail(DetailView):
	context_object_name = 'pin'
	template_name = 'pinteresting/pin_detail.html'

	def get_object(self):
		return get_object_or_404(Pin, pk = self.kwargs['pk'])

	def get_context_data(self, **kwargs):
		user_id = self.request.user.id
		pin = get_object_or_404(Pin, pk = self.kwargs['pk'])
		cur_user = False
		if int(pin.created_by.id) == user_id:
			cur_user = True

		context = super(PinDetail, self).get_context_data(**kwargs)

		if user_id is not None:
			user = self.request.user
			context['user'] = user

		context['user_boards'] = Board.objects.filter(created_by__id = user_id)
		context['cur_user'] = cur_user
		context['comments'] = Comment.objects.filter(pin = pin)
		
		return context


class CreateBoard(CreateView):
	model = Board
	template_name = 'pinteresting/board_create.html'
	form_class = AddBoard

	def get_form(self, form_class):
		user = self.request.user
		form = super(CreateBoard, self).get_form(form_class)
		form.instance.created_by = user
		return form

	def get_context_data(self, **kwargs):
		user = self.request.user
		context = super(CreateBoard, self).get_context_data(**kwargs)
		context['user_boards'] = Board.objects.filter(created_by = user)
		return context

	def form_valid(self, form):
		messages.success(self.request, 'Board successfully created!')
		return super(CreateBoard, self).form_valid(form)
	
	def form_invalid(self, form):
		messages.error(self.request, 'Something went wrong please try again!')
		return super(CreateBoard, self).form_invalid(form)

	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(CreateBoard, self).dispatch(*args, **kwargs)

class CreatePin(CreateView):
	model = Pin
	template_name = 'pinteresting/pin_create.html'
	form_class = AddPin

	def get_form(self, form_class):
		user = self.request.user
		form = super(CreatePin, self).get_form(form_class)
		form.instance.created_by = user
		form.fields['board'].queryset = Board.objects.filter(created_by = user)
		return form

	def get_context_data(self, **kwargs):
		user = self.request.user
		boards_avail = False
		for board in Board.objects.all():#checking all boards to see if current user has any
			if int(board.created_by.id) == int(user.id):
				boards_avail = True
				break

		context = super(CreatePin, self).get_context_data(**kwargs)
		context['user_boards'] = Board.objects.filter(created_by = user)
		context['boards_avail'] = boards_avail
		return context

	def form_valid(self, form):
		messages.success(self.request, 'Pin successfully created!')
		return super(CreatePin, self).form_valid(form)
	
	def form_invalid(self, form):
		messages.error(self.request, 'Something went wrong please try again!')
		return super(CreatePin, self).form_invalid(form)

	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(CreatePin, self).dispatch(*args, **kwargs)


class EditPin(UpdateView):
	model = Pin
	template_name = 'pinteresting/pin_update.html'
	form_class = EditPin

	def get_form(self, form_class):
		user = self.request.user
		form = super(EditPin, self).get_form(form_class)
		form.instance.created_by = user
		form.fields['board'].queryset = Board.objects.filter(created_by = user)
		return form

	def get_context_data(self, **kwargs):
		user = self.request.user
		boards_avail = False
		for board in Board.objects.all():#checking all boards to see if current user has any
			if int(board.created_by.id) == int(user.id):
				boards_avail = True
				break
		pin = get_object_or_404(Pin, pk = self.kwargs['pk'])
		cur_user = False
		if int(pin.created_by.id) == int(user.id):
			cur_user = True
		context = super(EditPin, self).get_context_data(**kwargs)
		context['user_boards'] = Board.objects.filter(created_by = user)
		context['boards_avail'] = boards_avail
		context['cur_user'] = cur_user
		return context

	def form_valid(self, form):
		messages.success(self.request, 'Pin successfully updated!')
		return super(EditPin, self).form_valid(form)
	
	def form_invalid(self, form):
		messages.error(self.request, 'Something went wrong please try again!')
		return super(EditPin, self).form_invalid(form)

	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(EditPin, self).dispatch(*args, **kwargs)


class DeletePin(DeleteView):
	model = Pin
	success_url = reverse_lazy('pinteresting:index')

	def get_context_data(self, **kwargs):
		user = self.request.user
		pin = get_object_or_404(Pin, pk = self.kwargs['pk'])
		cur_user = False
		if int(pin.created_by.id) == int(user.id):
			cur_user = True
		context = super(DeletePin, self).get_context_data(**kwargs)
		context['cur_user'] = cur_user
		return context

	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(DeletePin, self).dispatch(*args, **kwargs)


class RePin(CreateView):#mixin
	model = Pin
	template_name = 'pinteresting/repin.html'
	form_class = Repin

	def get_form(self, form_class):
		user = self.request.user
		pin = get_object_or_404(Pin, pk = self.kwargs['pk'])
		form = super(RePin, self).get_form(form_class)
		form.fields['board'].queryset = Board.objects.filter(created_by = user)
		form.instance.created_by = user #copying all the details over
		form.instance.title = pin.title
		form.instance.image = pin.image
		form.instance.description = "Repinned from " + str(pin.created_by) + ": " + str(pin.description)
		form.instance.link = pin.link
		form.instance.color = pin.color
		return form

	def get_context_data(self, **kwargs):
		user = self.request.user
		boards_avail = False
		for board in Board.objects.all():#checking all boards to see if current user has any
			if int(board.created_by.id) == int(user.id):
				boards_avail = True
				break

		context = super(RePin, self).get_context_data(**kwargs)
		context['user_boards'] = Board.objects.filter(created_by = user)
		context['boards_avail'] = boards_avail
		return context

	def form_valid(self, form):
		self.object = form.save(commit=False)
		messages.success(self.request, 'Pin successfully repinned!')
		return super(RePin, self).form_valid(form)

	def form_invalid(self, form):
		messages.error(self.request, 'Something went wrong please try again!')
		return super(RePin, self).form_invalid(form)

	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(RePin, self).dispatch(*args, **kwargs)

class CreateComment(CreateView):
	model = Comment
	template_name = 'pinteresting/comment_create.html'
	form_class = CommentForm

	def get_form(self, form_class):
		user = self.request.user
		pin = get_object_or_404(Pin, pk = self.kwargs['pin_id'])
		form = super(CreateComment, self).get_form(form_class)
		form.instance.user = user
		form.instance.pin = pin
		return form

	def get_context_data(self, **kwargs):
		user = self.request.user
		pin = get_object_or_404(Pin, pk = self.kwargs['pin_id'])
		context = super(CreateComment, self).get_context_data(**kwargs)
		context['user_boards'] = Board.objects.filter(created_by = user)
		context['pin'] = pin
		return context

	def form_valid(self, form):
		messages.success(self.request, 'Comment successfully added!')
		return super(CreateComment, self).form_valid(form)
	
	def form_invalid(self, form):
		messages.error(self.request, 'Something went wrong please try again!')
		return super(CreateComment, self).form_invalid(form)

	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(CreateComment, self).dispatch(*args, **kwargs)


class DeleteComment(DeleteView):
	model = Comment
	success_url = reverse_lazy('pinteresting:index')

	def get_context_data(self, **kwargs):
		user = self.request.user
		comment = get_object_or_404(Comment, pk = self.kwargs['pk'])
		cur_user = False
		if int(comment.user.id) == int(user.id):
			cur_user = True
		context = super(DeleteComment, self).get_context_data(**kwargs)
		context['cur_user'] = cur_user
		return context
	
	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):

pinteresting/templates/pinteresting/_pin.html
<li class="pin {{pin.color}}">
    <h3>{{pin.title}}</h3>
    <img src="{{ MEDIA_URL }}{{ pin.image }}" class="pin-image" />
    <br /><br />
    <div class="info">
        By: <span> &nbsp; {{ pin.created_by.username }} &nbsp; </span> On: &nbsp; {{ pin.pub_date }}<br/>
	{% if pin.link %}
		<span class="link"><a href="{{pin.link}}">Go to link</a></span>
		<br />
	{% endif %}
        <span class="board-name">{{ pin.board.name }}</span>
    
    {{ pin.description|linebreaks }}
	</div>
    {% if pin.comment_set.all %}
        <hr>
        {% for comment in pin.comment_set %}
        <span class="user">{{ comment.user }}</span> said:<br/>
        {{ comment.comment|linebreaksbr }}
        {% endfor %}
    {% endif %}
    <div style="clear: both;"></div>
</li>

pinteresting/templates/pinteresting/board_create.html
{% extends "base.html" %}

{% block content %}
<div class="input">
	<h1>Create a new Board</h1>
	<form method="POST" action="." id="board-add-form">
		<table class="form">
		{% csrf_token %}
		{{form}}
		</table>
		<input class="btn" type="submit" value="Create"></input>
	</form>
</div>
{% endblock %}

pinteresting/templates/pinteresting/board_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{board.name}}{% endblock %}

{% block scripts %}
<script src="http://masonry.desandro.com/masonry.pkgd.min.js"></script>
<script>
$(window).load(function() {
    var $container = $('#pin-list-head');
    $container.masonry({
        itemSelector: '.pin'
    });
});
</script>

<script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
<script>$.endlessPaginate({paginateOnScroll: true});</script>
{% endblock scripts %}

{% block content %}
	<div class="title">
	<h1 id="pin-top">{{board.name}}</h1>
	<h3>Created by: {{board.created_by}}</h3>
	</div>
	{% if board.pins %}
		<ul id="pin-list-head">
			{% if cur_user %}
		    		{% for pin in board.pins %}<!--this is what the boards owner will see-->
					<li class="pin {{pin.color}}">
				    <a href="{% url 'pinteresting:pin_detail' pin.id %}"><h3>{{pin.title}}</h3></a>
				    <img src="{{ MEDIA_URL }}{{ pin.image }}" class="pin-image" />
				    <br /><br />
				    <div class="info">
					By: <span> &nbsp; {{ pin.created_by.username }} &nbsp; </span> On: &nbsp; {{ pin.pub_date }}<br />
					
					<span class="board-name">Board(s): &nbsp;-{% for board in pin.boards %} <a href="{% url 'pinteresting:board_detail' board.id %}">{{ board.name }}</a>-{% endfor %}</span><br />
					{% if pin.link %}
						<span class="link"><a href="{{pin.link}}">Go to link</a></span><br />
						
					{% endif %}
				    	<br />
					</div>
				    	<p class="desc">{{ pin.description }}</p>
				        <a href="{% url 'pinteresting:pin_detail' pin.id %}"><p class="com">Comments: {{pin.num_comments}}</p></a>
				    <div style="clear: both;"></div>
				</li>
				{% endfor %}

			{% else %}
				{% for pin in board.public_pins %}<!--this is what a user who does not own the board will see -->
					<li class="pin {{pin.color}}">
				    <a href="{% url 'pinteresting:pin_detail' pin.id %}"><h3>{{pin.title}}</h3></a>
				    <a href="{% url 'pinteresting:pin_detail' pin.id %}"><img src="{{ MEDIA_URL }}{{ pin.image }}" class="pin-image" /></a>
				    <br /><br />
				    <div class="info">
					By: <span> &nbsp; {{ pin.created_by.username }} &nbsp; </span> On: &nbsp; {{ pin.pub_date }}<br />
					
					<span class="board-name">Board(s): &nbsp;{% for board in pin.boards %} <a href="{% url 'pinteresting:board_detail' board.id %}">{{ board.name }}</a>{% endfor %}</span><br />
					{% if pin.link %}
						<span class="link"><a href="{{pin.link}}">Go to link</a></span><br />
						
					{% endif %}
				    	<br />
					</div>
				    	<p class="desc">{{ pin.description }}</p>
				    
				    <div style="clear: both;"></div>
				</li>
				{% endfor %}
			{% endif %}
        			
		</ul>
	{% else %}
		<div class="problem"><p>No pins have been uploaded, please <a href="{% url 'pinteresting:add_pin' %}">create a new pin!</a></p></div>
	{% endif %}
{% endblock %}

pinteresting/templates/pinteresting/comment_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="input">
	{% if cur_user %}
	<h1>Delete Comment</h1>
	<form action="" method="post">{% csrf_token %}
    		<p>Are you sure you want to delete "{{ object }}"?</p>
    		<input type="submit" value="Confirm" />
	</form>
	{% else %}
		<h1>You do not own this comment and therefore cannot delete it!</h1>
	{% endif %}
</div>
{% endblock %}

pinteresting/templates/pinteresting/comment_create.html
{% extends "base.html" %}

{% block content %}
<div class="input">
	<h1>Comment on {{pin.title}}</h1>
	<form method="POST" action="." id="comment-add-form">
		<table class="form">
		{% csrf_token %}
		{{form}}
		</table>
		<input class="btn" type="submit" value="Comment"></input>
	</form>
</div>
{% endblock %}

pinteresting/templates/pinteresting/comment_update.html
{% extends "base.html" %}

{% block content %}
<div class="input">
	<h1>Edit comment</h1>
	<form method="POST" action="." id="comment-edit-form">
		<table class="form">
		{% csrf_token %}
		{{form}}
		</table>
		<input class="btn" type="submit" value="Edit Comment"></input>
	</form>
</div>
{% endblock %}

pinteresting/templates/pinteresting/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Pinteresting Main Page{% endblock %}

{% block scripts %}
<script src="http://masonry.desandro.com/masonry.pkgd.min.js"></script>
<script>
$(window).load(function() {
    var $container = $('#pin-list-head');
    $container.masonry({
        itemSelector: '.pin'
    });
});
</script>

<script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
<script>$.endlessPaginate({paginateOnScroll: true});</script>
{% endblock scripts %}

{% block content %}
	<div class="title">
	<h1 id="pin-top">Latest Pins</h1>
	<p>Welcome to Pinteresting, the app that totally isn't a copy of pinterest(naming unrelated)!</p>
	</div>
	{% if pins %}
		<ul id="pin-list-head">
		    	{% for pin in pins %}
        			<li class="pin {{pin.color}}">
				    <a href="{% url 'pinteresting:pin_detail' pin.id %}"><h3>{{pin.title}}</h3></a>
				    <a href="{% url 'pinteresting:pin_detail' pin.id %}"><img src="{{ MEDIA_URL }}{{ pin.image }}" class="pin-image" /></a>
				    <br /><br />
				    <div class="info">
					By: <span> &nbsp; {{ pin.created_by.username }} &nbsp; </span> On: &nbsp; {{ pin.pub_date }}<br />
					
					<span class="board-name">Board(s): &nbsp;-{% for board in pin.boards %} <a href="{% url 'pinteresting:board_detail' board.id %}">{{ board.name }}</a>- {% endfor %}</span><br />
					{% if pin.link %}
						<span class="link"><a href="{{pin.link}}">Go to link</a></span><br />
						
					{% endif %}
				    	<br />
					</div>
				    	<p class="desc">{{ pin.description }}</p>
				    	<a href="{% url 'pinteresting:pin_detail' pin.id %}"><p class="com">Comments: {{pin.num_comments}}</p></a>
				    <!--<div style="clear: both;"></div>-->
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No pins have been uploaded, please <p><a href="{% url 'pinteresting:add_board' %}">Create a new board</a></p> to get started.</p>
	{% endif %}
{% endblock %}

pinteresting/templates/pinteresting/pin_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="input">
	{% if cur_user %}
	<h1>Delete {{pin.title}}</h1>
	<form action="" method="post">{% csrf_token %}
    		<p>Are you sure you want to delete "{{ object }}"?</p>
    		<input type="submit" value="Confirm" />
	</form>
	{% else %}
		<h1>You do not own this pin and therefore cannot delete it!</h1>
	{% endif %}
</div>
{% endblock %}

pinteresting/templates/pinteresting/pin_create.html
{% extends "base.html" %}

{% block content %}
<div class="input">
	{% if boards_avail %}
	<h1>Create a new Pin</h1>
	<form method="POST" action="." id="pin-add-form" enctype="multipart/form-data">
		<table class="form">
		{% csrf_token %}
		{{form}}
		</table>
		<input class="btn" type="submit" value="Create"></input>
	</form>
	{% else %}
	<h3>It appears that you have not created any boards, please <a href="{% url 'pinteresting:add_board' %}">create a board</a> before creating your first pin.</h3>
	{% endif %}
</div>
{% endblock %}

pinteresting/templates/pinteresting/pin_detail.html
{% extends 'base.html' %}
{% load gravatar %}
{% load staticfiles %}

{% block title %}{{pin.title}}{% endblock %}


{% block content %}
	
	<div class="pin-detail {{pin.color}}">
	    
	    <h1 class="pin-title">{{pin.title}}</h1>
	    
	    <a href="{{pin.link}}"><img src="{{ MEDIA_URL }}{{ pin.image }}"/></a>
	    <br /><br />
	    <div>
		{% if not cur_user %}
			<a href="{% url 'pinteresting:repin' pin.id %}">Repin</a><br /><br />
		{% endif %}
		By: <span> &nbsp; {% gravatar_img_for_user pin.created_by 30 %} {{ pin.created_by.username }} &nbsp; </span> On: &nbsp; {{ pin.pub_date }}<br />
		
		<span class="board-name">Board(s): &nbsp;-{% for board in pin.boards %} <a href="{% url 'pinteresting:board_detail' board.id %}">{{ board.name }}</a>- {% endfor %}</span><br />
		{% if pin.link %}
			<span><a href="{{pin.link}}">Go to link</a></span><br />
			
		{% endif %}
	    	<br />
		</div>
	    	<p>{{ pin.description }}</p>
	    	
	    <div style="clear: both;"></div>
	    {% if cur_user %}
		<div class="update">
			<a href="{% url 'pinteresting:update_pin' pin.id %}">Edit Pin</a><br />
			<a href="{% url 'pinteresting:delete_pin' pin.id %}">Delete Pin</a>
		</div>
	    {% endif %}
		<div class="input">
		<h2>-Comments-</h2>
		{% if user.is_authenticated %}
			<p><a href="{% url 'pinteresting:add_comment' pin.id %}">Add a comment</a></p>
		{% endif %}
		{% if comments %}
			<table class="comments">
		    	{% for comment in comments %}
				<tr class="comments">
				<td>{% gravatar_img_for_user comment.user 30 %} {{comment.user}}:</td>
				<td>{{comment.comment}}</td>
				{% if user.id == comment.user.id %}
					<td><a href="{% url 'pinteresting:delete_comment' comment.id %}">Delete</a></td>
					<td><a href="{% url 'pinteresting:update_comment' comment.id %}">Edit</a></td>
				{% else %}
					<td></td>
					<td></td>
				{% endif %}
				
				<tr>
			{% endfor %}
		{% else %}
			<p class="comments">No one has left a comment on this pin, be the first to leave one!</p>
		{% endif %}
	    	</div>
	</div>


{% endblock %}

pinteresting/templates/pinteresting/pin_list.html
{% for pin in pins %}
        {% include 'pinteresting/_pin.html' %}
{% endfor %}

pinteresting/templates/pinteresting/pin_update.html
{% extends "base.html" %}

{% block content %}
<div class="input">
	{% if cur_user %}
	<h1>Update {{pin.title}}</h1>
	<form method="POST" action="." id="repin-add-form" enctype="multipart/form-data">
		<table class="form">
		{% csrf_token %}
		{{form}}
		</table>
		<input class="btn" type="submit" value="Update Pin"></input>
	</form>
	{% else %}
		<h1>You do not own this pin and therefore cannot update it!</h1>
	{% endif %}
</div>
{% endblock %}

pinteresting/templates/pinteresting/repin.html
{% extends "base.html" %}

{% block content %}
<div class="input">
	{% if boards_avail %}
	<h1>Repin a pin on your board</h1>
	<form method="POST" action="." id="repin-add-form" enctype="multipart/form-data">
		<table class="form">
		{% csrf_token %}
		{{form}}
		</table>
		<input class="btn" type="submit" value="Repin"></input>
	</form>
	{% else %}
	<h3>It appears that you have not created any boards, please <a href="{% url 'pinteresting:add_board' %}">create a board</a> before creating your first pin.</h3>
	{% endif %}
</div>
{% endblock %}